version: '3.8'
# database PostgreSQL version
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: pisethsattya
      POSTGRES_PASSWORD:  springboot
      POSTGRES_DB: advanced_jpa
    ports:
      - "5500:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck: # Add health check
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  postgres_data:
