SPRING_DATASOURCE_URL=jdbc:postgresql://advanced-jpa-db:5432/advanced_jpa_db
SPRING_DATASOURCE_USERNAME=pisethsattya
SPRING_DATASOURCE_PASSWORD=springboot

ALLOW_ORIGIN=*
ALLOW_METHOD=GET,POST,PATCH,DELETE
ALLOW_HEADER=*
