spring:
  application:
    name: spring-hateos-x-unit-test

  profiles:
    active: dev

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://advanced-jpa-db:5432/advanced_jpa_db}
    username: ${SPRING_DATASOURCE_USERNAME:pisethsattya}
    password: ${SPRING_DATASOURCE_PASSWORD:springboot}
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 60000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update   # dev only
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  security:
    allowed-origin: ${ALLOW_ORIGIN:*}
    allowed-method: ${ALLOW_METHOD:GET,POST,PATCH,DELETE}
    allowed-header: ${ALLOW_HEADER:*}

server:
  port: 8080
  ssl:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: docs
    display-request-duration: true
    default-model-expand-depth: 2
  api-docs:
    enabled: true
